Makefile.am: refactor .prerequisites_hcl target finding of updated files to only generate new ones when needed (work around "make" curiosities)
Signed-off-by: Jim Klimov <jimklimov@gmail.com>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -438,26 +438,41 @@ clean-local:
 # - NUT's manpages => .prerequisites_nut_ManHtmlPdf
 # - DDL manufacturers and models
 # Using one intermediate target to avoid two builds of same files
-# (and use of corrupted intermediate data) when running parallel:
+# (and use of corrupted intermediate data) when running parallel.
+# The touch-files are used to ensure updates only if something *really* changed
+# in the filesystem (always-running a .prerequisites_nut_ManHtmlPdf evaluation
+# causes always-running this target too):
 CLEANFILES += .prerequisites_hcl .prerequisites_hcl.start
 .prerequisites_hcl: nut/data/driver.list.in $(srcdir)/tools/nut-hclinfo.py $(MFR_TARGETS) Makefile | .prerequisites_nut_ManHtmlPdf
-	touch "$@.start"
-	+cd nut/data && $(MAKE) $(AM_MAKEFLAGS) driver.list
-	@if \
-	    python3 -c "import json,lxml"	\
-	 || python -c "import simplejson,lxml"	\
-	 || python -c "import json,lxml"	\
-	 || python2 -c "import simplejson,lxml"	\
-	 || python2 -c "import json,lxml"	\
-	; then	\
-		echo "Regenerating the HTML and JSON formated HCL tables.";	\
-		cd tools/ && ./nut-hclinfo.py;	\
-	else	\
-		echo "----------------------------------------------------------------------";	\
-		echo "Warning: either Python, or a required module (json, simplejson, lxml) ";	\
-		echo "is not available.";	\
-		echo "Skipping the HTML and JSON formated HCL tables regeneration.";	\
-		echo "----------------------------------------------------------------------";	\
+	@touch "$@.start"
+	@if [ -e .prerequisites_hcl ] ; then \
+		FOUND="`find $? nut/docs/man/*.html -newer .prerequisites_hcl -ls`" || exit 0 ; \
+		if [ -z "$${FOUND}" ] ; then \
+			rm -f "$@.start" ; \
+		else \
+			echo "Touching $@.start: FOUND=$${FOUND}" | tr '\n' ' ' ; echo "" ; \
+		fi ; \
+	 fi
+	@+if [ -e "$@.start" ] ; then \
+		( cd nut/data && $(MAKE) $(AM_MAKEFLAGS) driver.list ) || exit ; \
+		if \
+		   python3 -c "import json,lxml"	\
+		|| python  -c "import simplejson,lxml"	\
+		|| python  -c "import json,lxml"	\
+		|| python2 -c "import simplejson,lxml"	\
+		|| python2 -c "import json,lxml"	\
+		; then	\
+			echo "Regenerating the HTML and JSON formated HCL tables.";	\
+			cd tools/ && ./nut-hclinfo.py;	\
+		else	\
+			echo "----------------------------------------------------------------------";	\
+			echo "Warning: either Python, or a required module (json, simplejson, lxml) ";	\
+			echo "is not available.";	\
+			echo "Skipping the HTML and JSON formated HCL tables regeneration.";	\
+			echo "----------------------------------------------------------------------";	\
+		fi ; \
+	else \
+		echo "SKIP $@: no input files are actually newer than the existing .prerequisites_hcl" >&2 ; \
 	fi
 
 # These should be actually generated by nut-hclinfo.py above
@@ -469,7 +484,10 @@ CLEANFILES += .prerequisites_hcl .prerequisites_hcl.start
 # long as they still exist, or the input files were not updated):
 ups-html.txt scripts/ups_data.js: .prerequisites_hcl
 	test -s "$(@)"
-	@mv -f .prerequisites_hcl.start .prerequisites_hcl 2>/dev/null || true
+	@if [ -f .prerequisites_hcl.start ] ; then \
+		mv -f .prerequisites_hcl.start .prerequisites_hcl 2>/dev/null || true ; \
+	 fi
+#touch "$@"
 
 # Report each rebuild by depending on the Makefile
 index.html: website.txt news.txt Makefile $(LAYOUT).conf historic-release.txt
